[project]
name = "crispdm-linear-regression-demo"
version = "0.1.0"
description = "CRISP-DM simple linear regression with Streamlit UI"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

